openapi: 3.0.0
info:
    title: Private information
    version: 1.0.0
tags:
    - name: info
      description: Private information
paths:
    /:
        summary: Private information of the application
        description: retrieving private information from the application
        get:
            security:
                - token-authentification: []
            tags:
                - administration
                - info
            summary: Private information of the application
            description: retrieving private information from the application
            responses:
                200:
                    $ref: "responses.yml#/info"
                401:
                    $ref: "#/components/responses/unauthorizedError"
