openapi: 3.0.0
info:
    title: Api test
    version: 1.0.0
servers: [{ url: /v1 }]
tags:
    - name: administration
      description: Accès administrateur seulement
components:
    securitySchemes:
        $ref: "security-schemes.yml"
    responses:
        $ref: "responses.yml"
paths: {}
